Repository badgio/nandayus, pull requests merged in 2020-12, with the labels that each got.

#60 Light styling & banner creation
  src/App.vue
  src/components/Collection.vue
  src/components/Form.vue
  src/components/ManagementCard.vue
  src/components/TemplateCard.vue
  src/components/Templates.vue
Labels: enhancement

#65 ManagementCard implementation, CSS changes to Form.vue, Profile page, ...
  src/components/Badge.vue
  src/components/Collection.vue
  src/components/Contact.vue
  src/components/Form.vue
  src/components/Location.vue
  src/components/ManagementCard.vue
  src/components/Profile.vue
  src/router/index.js
Labels: enhancement, must

#88 ObjectPage creation, a lot of HTTP Requests, removal of several Components, structural changes...
  README.md
  src/components/Badge.vue
  src/components/BadgeCard.vue
  src/components/BarChart.vue
  src/components/Collection.vue
  src/components/CollectionCard.vue
  src/components/Contact.vue
  src/components/Footer.vue
  src/components/Form.vue
  src/components/Home.vue
  src/components/LineChart.vue
  src/components/Location.vue
  src/components/ManagementCard.vue
  src/components/Navbar.vue
  src/components/ObjectPage.vue
  src/components/PageNotFound.vue
  src/components/Profile.vue
  src/components/Reward.vue
  src/components/SignIn.vue
  src/components/SignUp.vue
  src/components/Statistics.vue
  src/components/TemplateCard.vue
  src/components/Templates.vue
  src/router/index.js
Labels: enhancement

#94 Deployment status badge and link
  README.md
Labels: documentation

#97 HTTP Requests, Redirections etc etc,
  src/components/Form.vue
  src/components/Navbar.vue
  src/components/ObjectPage.vue
  src/components/Statistics.vue
  src/router/index.js
Labels: enhancement
