Repository badgio/nandayus, pull requests merged in 2020-11, with the labels that each got.

#10 Fr/new location
  jest.config.js
  package-lock.json
  package.json
  src/App.vue
  src/components/Home.vue
  src/components/NewLocation.vue
  src/components/TemplateCard.vue
  src/router/index.js
  tests/unit/home.spec.js
  vue.config.js
Labels: enhancement

#14 Fr/locations v1
  src/App.vue
  src/components/Locations.vue
  src/components/Navbar.vue
  src/components/NewLocation.vue
  src/components/TemplateCard.vue
  src/router/index.js
Labels: enhancement

#17 Form Validity V1
  src/components/Navbar.vue
  src/components/NewLocation.vue
Labels: enhancement

#20 Fr/location v1
  package-lock.json
  package.json
  src/components/Location.vue
  src/components/NewLocation.vue
  src/main.js
  src/router/index.js
Labels: enhancement

#29 Removed Vuetify out of Navbar
  src/components/Navbar.vue
Labels: bug

#30 Fr/footer v1
  package-lock.json
  package.json
  src/App.vue
  src/components/Footer.vue
  src/components/Locations.vue
  src/components/Navbar.vue
  src/components/TemplateCard.vue
  src/main.js
  src/plugins/vuetify.js
Labels: enhancement

#31 Fr/location statistics v1
  package-lock.json
  package.json
  src/components/LineChart.vue
  src/components/LocationStatistics.vue
  src/router/index.js
Labels: enhancement

#33 Locations no longer has the 'backing' bug
  src/components/Badges.vue
  src/components/Footer.vue
  src/components/Location.vue
  src/components/LocationStatistics.vue
  src/components/Locations.vue
  src/components/NewBadge.vue
  src/components/NewLocation.vue
  src/components/SignIn.vue
  src/components/SignUp.vue
  src/components/TemplateCard.vue
Labels: bug

#36 Collections Listing Page + Responsive Navbar
  src/components/Collections.vue
  src/components/Navbar.vue
  src/router/index.js
Labels: enhancement

#37 Fr/new collection v1
  src/components/BadgeCard.vue
  src/components/Badges.vue
  src/components/Collection.vue
  src/components/Collections.vue
  src/components/Locations.vue
  src/components/NewCollection.vue
  src/components/NewLocation.vue
  src/components/TemplateCard.vue
  src/router/index.js
Labels: enhancement

#39 Badge management page
  package-lock.json
  src/components/Badge.vue
  src/components/Badges.vue
  src/components/NewBadge.vue
  src/components/NewCollection.vue
  src/components/SignIn.vue
  src/components/SignUp.vue
  src/router/index.js
Labels: enhancement

#40 Early stages of changing display Language
  src/components/Badges.vue
  src/components/Collection.vue
  src/components/Collections.vue
  src/components/Footer.vue
  src/components/Location.vue
  src/components/LocationStatistics.vue
  src/components/Locations.vue
  src/components/Navbar.vue
  src/components/NewBadge.vue
  src/components/NewCollection.vue
  src/components/NewLocation.vue
  src/components/SignIn.vue
  src/components/SignUp.vue
  src/components/TemplateCard.vue
  src/store/index.js
Labels: enhancement

#42 Filter implemented in several pages, fixed navbar items & light styling in several pages
  src/components/Badge.vue
  src/components/Badges.vue
  src/components/Collection.vue
  src/components/Collections.vue
  src/components/Location.vue
  src/components/Locations.vue
  src/components/Navbar.vue
Labels: enhancement

#50 README.md is better now
  README.md
Labels: must
